# Generated by Django 4.1.3 on 2023-10-27 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0002_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='makanan',
            new_name='barang',
        ),
    ]
