# Generated by Django 4.1.3 on 2023-10-28 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='makanan',
            name='stok',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minuman',
            name='stok',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='makanan',
            name='gambar',
            field=models.ImageField(upload_to='menu/images/'),
        ),
        migrations.AlterField(
            model_name='minuman',
            name='gambar',
            field=models.ImageField(upload_to='menu/images/'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('makanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.makanan')),
            ],
        ),
    ]
