# Generated by Django 4.1.3 on 2023-10-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=250)),
                ('nomor_rekam_medis', models.CharField(max_length=250)),
                ('alamat', models.CharField(max_length=250)),
                ('jenis_kelamin', models.CharField(max_length=250)),
                ('tanggal_lahir', models.DateField()),
                ('dokter', models.CharField(max_length=250)),
                ('departemen', models.CharField(max_length=250)),
                ('diagnosa', models.CharField(max_length=250)),
                ('nomor_ruangan', models.CharField(max_length=250)),
                ('jam', models.TimeField()),
                ('tindakan', models.CharField(max_length=250)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
