# Generated by Django 4.1.3 on 2023-10-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='makanan',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
