# Generated by Django 4.1.3 on 2023-10-27 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0002_makanan_deskripsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('makanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makanan.makanan')),
            ],
        ),
    ]
